### ISSUE TITLE
'Back to dashboard' button doesn't go back to dashboard

### ISSUE THREAD

**Issue by Crystalsage** [CSI-CATT-DMCE/Care4U#7]
# Problem
In the [DashProfile.java](https://github.com/CSI-CATT-DMCE/Care4U/blob/main/app/src/main/java/com/example/innovathon2022_care4u/DashProfile.java) activity, there's a button which is supposed to take you back to the dashboard. It doesn't.

## Potential fix
Make the button go back to the dashboard. Make sure your fix takes care of the back stack.

**Comment by iremugurlu** [comment]
Hey, I'm interested. Can you assign this one to me?
