### ISSUE TITLE
Fix logout backstack

### ISSUE THREAD

**Issue by Crystalsage** [CSI-CATT-DMCE/Care4U#8]
# Problem
There is a logout button in 'My profile' section. Currently, it takes you back to the login screen. 

![image](https://user-images.githubusercontent.com/51860725/196733054-d4315383-a1d5-4367-8822-0f8efc8de390.png)

However, it doesn't exactly log out as the user can still press back button to take them back to the dashboard.

**To reproduce**: 
1. Go to 'My profile' section. 
2. Press 'Logout'.
3. Once you're on the Login screen, press back button.

## Potential solution
Clear the backstack as we reach the login screen.

**Comment by yashnerkar** [comment]
I would like to work on this issue
